a = "Shayna"
b = len(a)  # length of string
print("Length of Shayna", b)
c = a.upper()  # return upper all string
print("shayna in upper case is", c)
d = a.replace("Shayna", "Nitin")
print("shayna and", d, "are one soul in different body")
e = a.swapcase()
print(e)
f = a.isalpha()
print(f)
g = a.isalnum()
print(g)
h = a.isdigit()
print(h)
i = a.isidentifier()  # it return boolean on the basis of rule of making an identifier
print(i)
j = a.isnumeric()
print(j)
k = a.index("S")
print(k)
l = a.strip()
print(l)
m = a.lstrip()
print(m)
n = a.split("h")
print(n)
o = a.join("Nn")
print(o)
